# Generated by Django 4.2 on 2023-05-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Training Date')),
                ('training', models.CharField(choices=[('M', 'Morning'), ('D', 'Day'), ('E', 'Evening')], default='M', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
